/* Copyright 2015 Samsung Electronics Co., LTD
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.gearvrf.accessibility;

import org.gearvrf.GVRAndroidResource;
import org.gearvrf.GVRContext;
import org.gearvrf.GVRMaterial.GVRShaderType.Texture;
import org.gearvrf.GVRMesh;
import org.gearvrf.GVRSceneObject;
import org.gearvrf.GVRTexture;

/**
 * {@code GVRAccessibilityObject} responsible to represent an Accessibility
 * scene object.
 * <p>
 */
public class GVRAccessibilityObject extends GVRSceneObject {

    private GVRAccessibilityTextSpeech mTextSpeech;

    /**
     * Constructs a scene object with {@linkplain GVRMesh an arbitrarily complex
     * geometry} that uses the standard {@linkplain Texture 'texture shader'} to
     * display a {@linkplain GVRTexture texture.}
     * 
     * @param gvrContext current {@link GVRContext}
     * @param gvrMesh a {@link GVRMesh} - usually generated by one of the
     *            {@link GVRContext#loadMesh(GVRAndroidResource)} methods, or
     *            {@link GVRContext#createQuad(float, float)}
     * @param texture a {@link GVRTexture}
     */
    public GVRAccessibilityObject(GVRContext gvrContext, GVRMesh gvrMesh, GVRTexture texture) {
        super(gvrContext, gvrMesh, texture);
    }

    /**
     * Set the {@link GVRAccessibilityTExtSpeech}
     * 
     * @param mTextSpeech
     */
    public void setTextSpeech(GVRAccessibilityTextSpeech mTextSpeech) {
        this.mTextSpeech = mTextSpeech;
    }

    /**
     * @return the object {@link GVRAccessibilityTextSpeech}
     */
    public GVRAccessibilityTextSpeech getTextSpeech() {
        return this.mTextSpeech;
    }
}
